import { ProColumns } from '@ant-design/pro-components';
import type Record from '../../../types/record';

export const getRecordColumns = (
): ProColumns<Record>[] => [
  {
    title: 'Төлөв',
    dataIndex: 'status',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Төрөл',
    dataIndex: 'type',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Баримт дугаар',
    dataIndex: 'documentNumber',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Огноо',
    dataIndex: 'date',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Нийт төлсөн',
    dataIndex: 'totalPaid',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Бэлнээр',
    dataIndex: 'cash',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Бэлэн бусаар',
    dataIndex: 'nonCash',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Нийт төлбөр',
    dataIndex: 'totalAmount',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Краны хөлс',
    dataIndex: 'craneFee',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Зам талбай ашиглалт',
    dataIndex: 'roadAreaUsage',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Ачаа хадгаламж',
    dataIndex: 'cargoStorage',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Чингэлэг вагон цэвэрлэгээ',
    dataIndex: 'containerWagonCleaning',
    width: 200,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Вагон ашиглалт',
    dataIndex: 'wagonUsage',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'TL Вагон ашиглалт',
    dataIndex: 'tlWagonUsage',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Гаалийн үзлэг',
    dataIndex: 'customsInspection',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Авто ачигч',
    dataIndex: 'forklift',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
  {
    title: 'Машин оролт',
    dataIndex: 'vehicleEntry',
    width: 150,
    sorter: true,
    showSorterTooltip: false,
  },
];
